### ISSUE TITLE
Issue with fine tuning the model.

### ISSUE THREAD

**Issue by temp07259** [google-research/timesfm#242]
Hello @misha-chertushkin ,
Following a discussion with @rajatsen91 regarding the fine-tuning issue, he suggested I include you in the loop for further assistance.

I am currently working on fine-tuning the model based on the reference from the **finetuning_torch.ipynb** notebook. However, I am encountering an error when trying to execute the following line:
`from timesfm.finetuning_torch import FinetuningConfig, TimesFMFinetuner`

The error message displayed is:
`ModuleNotFoundError: No module named 'timesfm.finetuning_torch`

**Steps Taken So Far:**
1. I have tried installing the timesfm package.
2. I also cloned the repository to ensure I have the latest version of the code.
3. I verified that I am using a compatible version of Python (>3.11.X) as recommended.
4. Other packages have been installed successfully without issues.

**Input from @rajatsen91 :-**
 It seems that the (a) the current pypi package has not been updated with the pytorch fine-tuning support 
(b) the finetuning folder is being ignored during installation due to this **(https://github.com/google-research/timesfm/blob/master/pyproject.toml#L2) : name = "timesfm"**

Could you please provide any further guidance or troubleshooting steps to resolve this error? Your help in resolving this issue would be greatly appreciated so I can continue with the fine-tuning process.

Thank you for your time and assistance!

Best regards,
Rahul Raj

**Comment by misha-chertushkin** [comment]
Thanks for flagging this issue :) I have just fixed it in https://github.com/google-research/timesfm/pull/243, the problem was in wrong import. I have just launched the cells in notebook and confirmed it works. Screenshot attached below.

Once the PR is merged by @rajatsen91 you should be good to go. 

If you need the fix asap, just try to fix the first line in the import section from `timesfm.finetuning_torch` to `finetuning.finetuning_torch` (but better to wait for PR to be merged)

Hope it helps! :)

<img width="1336" alt="Image" src="https://github.com/user-attachments/assets/3f705b3b-56ba-4300-be6d-9db529b5441b" />

**Comment by temp07259** [comment]
Thank you for resolving the issue promptly. I appreciate your assistance in identifying and fixing the problem. It would be great if you could notify me once the PR is merged.

Thanks again for your help! :)

**Comment by temp07259** [comment]
I am still facing the issue in running the code from **finetuning_torch.ipynb**
```
from os import path
from typing import Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.multiprocessing as mp
import yfinance as yf
from finetuning.finetuning_torch import FinetuningConfig, TimesFMFinetuner
from huggingface_hub import snapshot_download
from torch.utils.data import Dataset

from timesfm import TimesFm, TimesFmCheckpoint, TimesFmHparams
from timesfm.pytorch_patched_decoder import PatchedTimeSeriesDecoder
import os
```

**Error :-**
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-8-563354815c1c>](https://localhost:8080/#) in <cell line: 0>()
      7 import torch.multiprocessing as mp
      8 import yfinance as yf
----> 9 from finetuning.finetuning_torch import FinetuningConfig, TimesFMFinetuner
     10 from huggingface_hub import snapshot_download
     11 from torch.utils.data import Dataset

ModuleNotFoundError: No module named 'finetuning'

**Comment by shahrokhvahabi** [comment]
Hello everyone. Thank you for sharing the code. I have the same problem with this error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[4], line 9
      7 import torch.multiprocessing as mp
      8 import yfinance as yf
----> 9 from finetuning.finetuning_torch import FinetuningConfig, TimesFMFinetuner
     10 from huggingface_hub import snapshot_download
     11 from torch.utils.data import Dataset

ModuleNotFoundError: No module named 'finetuning'

I would appreciate it if you could help me.

**Comment by misha-chertushkin** [comment]
@shahrokhvahabi @temp07259 We just created the PR https://github.com/google-research/timesfm/pull/247 to fix this issue. Once the PR is merged, please try again and let us know if the fix worked :) Thank you very much in advance!

**Comment by temp07259** [comment]
Hi @misha-chertushkin ,
I am still encountering the same issue. Would you mind checking it once more when you have a moment?

@shahrokhvahabi , are you still experiencing the same problem as well?
Thank you so much for your help in advance. I really appreciate it!

**Comment by misha-chertushkin** [comment]
@shahrokhvahabi @temp07259 I have just performed the clean experiment, which involved:
1) Creating completely new env
2) Installing the timesfm from pypi: "timesfm[torch]==1.2.9"
3) Creating the notebook and importing it, attaching the screenshot below.

<img width="1350" alt="Image" src="https://github.com/user-attachments/assets/4b7967e0-d050-4b81-bfd4-7bb89b0ec358" />
In this case it worked and was imported perfectly fine. Are you sure you installed the 1.2.9 version of timesfm after we fixed the issue? Let me know if this still does not help :)

**Comment by shahrokhvahabi** [comment]
Hi @misha-chertushkin. Thanks for your reply and apologize for my late answer. Now, it works well. But how can I enter my data? Is there any template for it?

**Comment by misha-chertushkin** [comment]
> Hi [@misha-chertushkin](https://github.com/misha-chertushkin). Thanks for your reply and apologize for my late answer. Now, it works well. But how can I enter my data? Is there any template for it?

@shahrokhvahabi yes :) We have provided the Dataset implementation in the `finetuning/finetuning_example.py`, all you need to do is just instantiate your own dataset and that's it :)

**Comment by temp07259** [comment]
Hi @misha-chertushkin Thank you for your reply, and apologies for my delayed response. The system is working well now, but I am facing a limitation during fine-tuning—I can’t use any context length other than 128. Could you please take a look at this?
Thank you so much in advance.

**Comment by temp07259** [comment]
Hi @misha-chertushkin,

I’m facing another issue while trying to load the model locally. I’ve downloaded the model and am attempting to load it using the checkpoint, but I’m encountering a "permission denied" error.

Could you please help me troubleshoot this?
Thanks in advance
